train_dataset:
  dataset:
    name: VCTK-single
    args:
      root_path: /data/datasets
  wrapper:
    name: audio-down
    args:
      coord_scale: 100
      sr_scale: 3
  batch_size: 1

val_dataset:
  dataset:
    name: VCTK-single
    args:
      root_path: /data/datasets
  wrapper:
    name: sr-implicit-audio-downsampled
    args:
      coord_scale: 100
      sr_scale: 3
  batch_size: 1

model:
  name: siren
  args:
    dim_in: 2
    dim_hidden: 512
    dim_out: 1
    num_layers: 7
    w0_initial: 30.0
    w0: 10.0

loss: l1_spec

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 3000
multi_step_lr:
  milestones: [500, 1000, 1500, 2000, 2500]
  gamma: 0.5


epoch_val: 100
epoch_save: 100
